language: node_js
node_js:
  - "node"

cache: npm
install:
  - npm install
  - npm install -g parcel

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master