language: node_js
node_js:
  - '12'

cache: 
  directories:
    - node_modules
    - ~/.npm
git:
  depth: 3
  
install:
  - npm ci
  - npm install
  - npm install -g parcel

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy elements"
  on:
    branch: master